project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
bundles:
  - 2
files:
  - source: main/Resources/Lang/en_US.json
    translation: /Resources/Lang/%locale_with_underscore%.json
    preserve_hierarchy: false
