project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
bundles:
  - 2
files:
  - source: /Resources/Lang/en_US.jsonc
    translation: /Resources/Lang/%locale_with_underscore%.jsonc
