namespace EHR
{
    public enum CustomRoles
    {
        // Default
        Crewmate = 0,

        // Impostors (Vanilla)
        Impostor,
        Phantom,
        Shapeshifter,

        // Vanilla Remakes
        ImpostorEHR,
        PhantomEHR,
        ShapeshifterEHR,

        // Impostors

        Abyssbringer,
        Hacker, // Anonymous
        AntiAdminer,
        Sans, // Arrogance
        Assumer,
        Augmenter,
        Bard,
        Blackmailer,
        Bomber,
        BountyHunter,
        OverKiller, // Butcher
        Camouflager,
        Capitalism,
        Cantankerous,
        Changeling,
        Chronomancer,
        Cleaner,
        Commander,
        EvilDiviner, // Consigliere
        Consort,
        Councillor,
        Crewpostor,
        CursedWolf,
        Deathpact,
        Devourer,
        Disperser,
        Duellist,
        Dazzler,
        Echo,
        Escapee,
        Eraser,
        EvilGuesser,
        EvilTracker,
        FireWorks,
        Framer,
        Freezer,
        Gambler,
        Gangster,
        Generator,
        Godfather,
        Greedier,
        Hangman,
        Hitman,
        Hypnotist,
        Inhibitor,
        Kamikaze,
        Kidnapper,
        Minimalism, // Killing Machine
        BallLightning, // Lightning
        Librarian,
        Lurker,
        Mafioso,
        Mastermind,
        Mafia, // Nemesis
        SerialKiller, // Mercenary
        Miner,
        Morphling,
        Assassin, // Ninja
        Nuker,
        Nullifier,
        Occultist,
        Overheat,
        Parasite,
        Penguin,
        Puppeteer,
        QuickShooter,
        Refugee,
        RiftMaker,
        Saboteur,
        Sapper,
        Scavenger,
        Silencer,
        Sniper,
        ImperiusCurse, // Soul Catcher
        Swapster,
        Swiftclaw,
        Swooper,
        Stealth,
        TimeThief,
        BoobyTrap, // Trapster
        Trickster,
        Twister,
        Underdog,
        Undertaker,
        Vampire,
        Ventriloquist,
        Vindicator,
        Visionary,
        Warlock,
        Wasp,
        Wildling,
        Witch,
        YinYanger,
        Zombie,

        // Crewmates (Vanilla)
        Engineer,
        GuardianAngel,
        Noisemaker,
        Scientist,
        Tracker,

        // Vanilla Remakes
        CrewmateEHR,
        EngineerEHR,
        GuardianAngelEHR,
        NoisemakerEHR,
        ScientistEHR,
        TrackerEHR,

        // Crewmates

        Addict,
        Adrenaline,
        Adventurer,
        Aid,
        Alchemist,
        Altruist,
        Analyst,
        Ankylosaurus,
        Autocrat,
        Bane,
        Beacon,
        Benefactor,
        Bodyguard,
        CameraMan,
        Car,
        Catcher,
        CyberStar, // Celebrity
        Chameleon,
        Chef,
        Clairvoyant,
        Cleanser,
        Convener,
        CopyCat,
        Bloodhound, // Coroner
        LovingCrewmate,
        LovingImpostor,
        Crusader,
        Dad,
        Demolitionist,
        Deputy,
        Detective,
        Detour,
        Dictator,
        Doctor,
        DonutDelivery,
        Doormaster,
        DovesOfNeace,
        Drainer,
        Druid,
        Electric,
        Enigma,
        Escort,
        Express,
        Farseer,
        Divinator, // Fortune Teller
        Gaulois,
        Goose,
        Grappler,
        Grenadier,
        GuessManagerRole,
        Guardian,
        Ignitor,
        Insight,
        ParityCop, // Inspector
        Inquirer,
        Jailor,
        Journalist,
        Judge,
        Needy, // Lazy Guy
        Leery,
        Lighter,
        Lookout,
        Luckey,
        Lyncher,
        Markseeker,
        Marshall,
        Mathematician,
        Mayor,
        SabotageMaster, // Mechanic
        Medic,
        Mediumshiper,
        Merchant,
        Monitor,
        Mole,
        Monarch,
        Mortician,
        NiceEraser,
        NiceGuesser,
        NiceHacker,
        NiceSwapper,
        Nightmare,
        Negotiator,
        Observer,
        Oracle,
        Oxyman,
        Paranoia,
        Perceiver,
        Philantropist,
        President,
        Psychic,
        Rabbit,
        Randomizer,
        Rhapsode,
        Ricochet,
        Safeguard,
        Scout,
        SecurityGuard,
        Sentinel,
        Sentry,
        Sheriff,
        Shiftguard,
        Snitch,
        Socialite,
        Soothsayer,
        Spiritualist,
        Speedrunner,
        SpeedBooster,
        Spy,
        SuperStar,
        TaskManager,
        Telekinetic,
        Tether,
        TimeManager,
        TimeMaster,
        ToiletMaster,
        Tornado,
        Transmitter,
        Transporter,
        Tracefinder,
        Tunneler,
        Ventguard,
        Veteran,
        SwordsMan, // Vigilante
        Whisperer,
        Witness,
        Wizard,

        // Neutrals

        Agitater,
        Amnesiac,
        Arsonist,
        Backstabber,
        Bandit,
        Bargainer,
        Beehive,
        BloodKnight,
        Bubble,
        Chemist,
        Cherokious,
        Collector,
        Curser,
        Deathknight,
        Gamer, // Demon
        Doppelganger,
        Doomsayer,
        Eclipse,
        Enderman,
        Evolver,
        Executioner,
        Totocalcio, // Follower
        Gaslighter,
        Glitch,
        God,
        FFF, // Hater
        HeadHunter,
        HexMaster,
        Hookshot,
        Imitator,
        Impartial,
        Innocent,
        Jackal,
        Jester,
        Jinx,
        Juggernaut,
        Konan,
        Lawyer,
        Magician,
        Mario,
        Maverick,
        Medusa,
        Mycologist,
        NecroGuesser,
        Necromancer,
        Nonplus,
        NoteKiller,
        Opportunist,
        Patroller,
        Pelican,
        Pestilence,
        Phantasm,
        Pickpocket,
        PlagueBearer,
        PlagueDoctor,
        Poisoner,
        Postman,
        Predator,
        Provocateur,
        Pursuer,
        Pyromaniac,
        QuizMaster,
        Reckless,
        Revolutionist,
        Ritualist,
        Rogue,
        Romantic,
        RouleteGrandeur,
        RuthlessRomantic,
        Samurai,
        SchrodingersCat,
        NSerialKiller, // Serial Killer
        Shifter,
        Sidekick,
        Simon,
        SoulHunter,
        Spiritcaller,
        Sprayer,
        DarkHide, // Stalker
        Succubus,
        Sunnyboy,
        Technician,
        Tank,
        Terrorist,
        Tiger,
        Traitor,
        Tremor,
        Vengeance,
        VengefulRomantic,
        Virus,
        Vortex,
        Vulture,
        Wraith,
        Werewolf,
        WeaponMaster,
        Weatherman,
        Workaholic,

        // Solo Kombat
        KB_Normal,

        // FFA
        Killer,

        // Move And Stop
        Tasker,

        // Hot Potato
        Potato,

        // H&S
        Hider,
        Seeker,
        Fox,
        Troll,
        Jumper,
        Detector,
        Jet,
        Dasher,
        Locator,
        Venter,
        Agent,
        Taskinator,

        // Speedrun
        Runner,

        // Capture The Flag
        CTFPlayer,

        // Natural Disasters
        NDPlayer,

        // Room Rush
        RRPlayer,

        // GM
        GM,

        // ????
        Convict,


        // Sub-role after 500
        NotAssigned = 500,
        Allergic,
        Antidote,
        AntiTP,
        Asthmatic,
        Autopsy,
        Avanger,
        Bait,
        Busy,
        Trapper, // Beartrap
        Bewilder,
        Bloodlust,
        Bloodmoon, // Ghost role
        Charmed,
        Circumvent,
        Cleansed,
        Clumsy,
        Contagious,
        Damocles,
        Deadlined,
        DeadlyQuota,
        Disco,
        Diseased,
        Dynamo,
        Unreportable, // Disregarded
        DoubleShot,
        Egoist,
        Energetic,
        EvilSpirit,
        Finder,
        Flashman,
        Fragile,
        Fool,
        Giant,
        Glow,
        Gravestone,
        GA, // Guardian Angel - Ghost role
        Guesser,
        Haste,
        Haunter, // Ghost role
        Introvert,
        Knighted,
        LastImpostor,
        Lazy,
        Lovers,
        Loyal,
        Lucky,
        Madmate,
        Magnet,
        Mare,
        Messenger,
        Mimic,
        Minion, // Ghost role
        Mischievous,
        Necroview,
        Nimble,
        Noisy,
        Oblivious,
        Onbound,
        Spurt,
        Sleep,
        Specter, // Ghost role
        Physicist,
        Rascal,
        Reach,
        Recruit,
        Rookie,
        Trainee,
        DualPersonality, // Schizophrenic
        Seer,
        Sleuth,
        Sonar,
        Stained,
        Taskcounter,
        TicketsStealer, // Stealer
        Stressed,
        Swift,
        Sunglasses,
        Brakar, // Tiebreaker
        Torch,
        Truant,
        Undead,
        Unlucky,
        Warden, // Ghost role
        Watcher,
        Workhorse,
        Youtuber
    }
}