namespace EHR;

public enum CustomRoles
{
    // Default
    Crewmate = 0,

    // Impostors (Vanilla)
    Impostor,
    Phantom,
    Shapeshifter,
    Viper,

    // Vanilla Remakes
    ImpostorEHR,
    PhantomEHR,
    ShapeshifterEHR,
    ViperEHR,

    // Impostors

    Abyssbringer,
    Ambusher,
    Anonymous,
    AntiAdminer,
    Arrogance,
    Assumer,
    Augmenter,
    Bard,
    Blackmailer,
    Bomber,
    BountyHunter,
    OverKiller, // Butcher
    Camouflager,
    Capitalism,
    Cantankerous,
    Centralizer,
    Changeling,
    Chronomancer,
    Cleaner,
    ClockBlocker,
    Commander,
    Consigliere,
    Consort,
    Councillor,
    Crewpostor,
    CursedWolf,
    Deathpact,
    Devourer,
    Disperser,
    Duellist,
    Dazzler,
    Echo,
    Escapee,
    Eraser,
    EvilGuesser,
    EvilTracker,
    Fabricator,
    FireWorks,
    Forger,
    Framer,
    Freezer,
    Gambler,
    Gangster,
    Generator,
    Godfather,
    Greedier,
    Hangman,
    Hitman,
    Hypnotist,
    Hypocrite,
    Inhibitor,
    Kamikaze,
    Kidnapper,
    KillingMachine,
    BallLightning, // Lightning
    Librarian,
    Loner,
    LovingImpostor,
    Lurker,
    Mafioso,
    Mastermind,
    Nemesis,
    Mercenary,
    Miner,
    Morphling,
    Ninja,
    Nuker,
    Nullifier,
    Occultist,
    Overheat,
    Parasite,
    Penguin,
    Postponer,
    Psychopath,
    Puppeteer,
    QuickShooter,
    Refugee,
    RiftMaker,
    Saboteur,
    Sapper,
    Scavenger,
    Silencer,
    Sniper,
    ImperiusCurse, // Soul Catcher
    Stasis,
    Swapster,
    Swiftclaw,
    Swooper,
    Stealth,
    TimeThief,
    BoobyTrap, // Trapster
    Trickster,
    Twister,
    Undertaker,
    Vampire,
    Venerer,
    Ventriloquist,
    Vindicator,
    Visionary,
    Warlock,
    Wasp,
    Wildling,
    Wiper,
    Witch,
    YinYanger,
    Zombie,

    // Crewmates (Vanilla)
    Engineer,
    GuardianAngel,
    Noisemaker,
    Scientist,
    Tracker,
    Detective,

    // Vanilla Remakes
    CrewmateEHR,
    EngineerEHR,
    GuardianAngelEHR,
    NoisemakerEHR,
    ScientistEHR,
    TrackerEHR,
    DetectiveEHR,

    // Crewmates

    Addict,
    Adrenaline,
    Adventurer,
    Aid,
    Alchemist,
    Altruist,
    Analyst,
    Ankylosaurus,
    Astral,
    Autocrat,
    Bane,
    Battery,
    Beacon,
    Benefactor,
    Bodyguard,
    CameraMan,
    Captain,
    Car,
    Catcher,
    Chameleon,
    Chef,
    Clairvoyant,
    Cleanser,
    Convener,
    CopyCat,
    Coroner,
    Crusader,
    Dad,
    Demolitionist,
    Deputy,
    Detour,
    Dictator,
    Doctor,
    DonutDelivery,
    Doorjammer,
    DoubleAgent,
    DovesOfNeace,
    Drainer,
    Druid,
    Electric,
    Enigma,
    Escort,
    Express,
    Farmer,
    Farseer, // Investigator
    Forensic,
    Divinator, // Fortune Teller
    Gardener,
    Gaulois,
    Goose,
    Grappler,
    Grenadier,
    MeetingManager,
    Guardian,
    Hacker,
    Helper,
    Ignitor,
    Imitator,
    Insight,
    ParityCop, // Inspector
    Inquirer,
    Inquisitor,
    Jailor,
    Journalist,
    Judge,
    Needy, // Lazy Guy
    Leery,
    Lighter,
    Lookout,
    LovingCrewmate,
    Luckey,
    Decryptor,
    Markseeker,
    Marshall,
    Mathematician,
    Mayor,
    Mechanic,
    Medic,
    Mediumshiper,
    Merchant,
    Monitor, // Telecommunication
    Mole,
    Monarch,
    Mortician,
    NiceEraser,
    NiceGuesser,
    NiceSwapper,
    Nightmare,
    Negotiator,
    Observer,
    Oracle,
    Oxyman,
    Paranoia,
    Perceiver,
    Philantropist,
    PortalMaker,
    President,
    Psychic,
    Rabbit,
    Randomizer,
    Retributionist,
    Rhapsode,
    Ricochet,
    Safeguard,
    Scout,
    SecurityGuard,
    Sentinel,
    Sentry,
    Sheriff,
    Shiftguard,
    Snitch,
    Socialite,
    Soothsayer,
    Spiritualist,
    Speedrunner,
    SpeedBooster,
    Spy,
    SuperStar,
    TaskManager,
    Telekinetic,
    Tether,
    TimeManager,
    TimeMaster,
    ToiletMaster,
    Tornado,
    Transmitter,
    Transporter,
    Tracefinder,
    Tree,
    Tunneler,
    Vacuum,
    Ventguard,
    Veteran,
    SwordsMan, // Vigilante
    Whisperer,
    Witness,
    Wizard,

    // Neutrals

    Agitater,
    Amnesiac,
    Amogus,
    Arsonist,
    Auditor,
    Backstabber,
    Bandit,
    Bargainer,
    Beehive,
    BloodKnight,
    Bubble,
    Chemist,
    Cherokious,
    Clerk,
    Collector,
    Curser,
    Dealer,
    Deathknight,
    Demon,
    Doppelganger,
    Doomsayer,
    Duality,
    Eclipse,
    Enderman,
    Evolver,
    Executioner,
    Explosivist,
    Follower,
    Gaslighter,
    Glitch,
    God,
    Hater,
    HeadHunter,
    HexMaster,
    Hookshot,
    Impartial,
    PlagueDoctor, // Infection
    Innocent,
    Investor,
    Jackal,
    Jester,
    Jinx,
    Juggernaut,
    Konan,
    Lawyer,
    Magician,
    Magistrate,
    Mario,
    Maverick,
    Medusa,
    Mycologist,
    NecroGuesser,
    Necromancer,
    Nonplus,
    NoteKiller,
    Opportunist,
    Patroller,
    Pawn,
    Pelican,
    Pestilence,
    Phantasm,
    Pickpocket,
    PlagueBearer,
    Poisoner,
    Postman,
    Predator,
    Provocateur,
    Pulse,
    Pursuer,
    Pyromaniac,
    QuizMaster,
    Reckless,
    Revolutionist,
    Ritualist,
    Rogue,
    Romantic,
    RoomRusher,
    RouleteGrandeur,
    RuthlessRomantic,
    Samurai,
    SchrodingersCat,
    Seamstress,
    SerialKiller,
    Sharpshooter,
    Shifter,
    Sidekick,
    Simon,
    Slenderman,
    SoulHunter,
    Spirit,
    Spiritcaller,
    Sprayer,
    Stalker,
    Starspawn,
    Cultist,
    Sunnyboy,
    Technician,
    Tank,
    Terrorist,
    Thanos,
    Tiger,
    Traitor,
    Tremor,
    Vengeance,
    VengefulRomantic,
    Virus,
    Vortex,
    Vulture,
    Wraith,
    Werewolf,
    WeaponMaster,
    Weatherman,
    Workaholic,

    // Coven

    Augur,
    Banshee,
    CovenLeader,
    CovenMember,
    Death, // Reaper changes to Death
    Dreamweaver,
    Enchanter,
    Goddess,
    Illusionist,
    Poache,
    PotionMaster,
    Reaper,
    Siren,
    SpellCaster,
    Timelord,
    VoodooMaster,
    Wyrd,

    // Solo Kombat
    KB_Normal,

    // FFA
    Killer,

    // Move And Stop
    Tasker,

    // Hot Potato
    Potato,

    // H&S
    Hider,
    Seeker,
    Fox,
    Troll,
    Jumper,
    Detector,
    Jet,
    Dasher,
    Locator,
    Venter,
    Agent,
    Taskinator,

    // Speedrun
    Runner,

    // Capture The Flag
    CTFPlayer,

    // Natural Disasters
    NDPlayer,

    // Room Rush
    RRPlayer,

    // King of the Zones
    KOTZPlayer,

    // Quiz
    QuizPlayer,

    // The Mind Game
    TMGPlayer,

    // Bed Wars
    BedWarsPlayer,
    
    // Deathrace
    Racer,
    
    // Mingle
    MinglePlayer,

    // GM
    GM,

    // ????
    Convict,


    // Sub-role after 500
    NotAssigned = 500,
    Aide,
    Allergic,
    Anchor,
    Antidote,
    AntiTP,
    Asthmatic,
    Autopsy,
    Avanger,
    Bait,
    BananaMan,
    Trapper, // Beartrap
    Bewilder,
    Blind,
    Blocked,
    Bloodlust,
    Bloodmoon, // Ghost role
    Busy,
    Charmed,
    Circumvent,
    Cleansed,
    Clumsy,
    Commited,
    Compelled,
    Composter,
    Concealer,
    Contagious,
    Damocles,
    Deadlined,
    DeadlyQuota,
    Disco,
    Diseased,
    Dynamo,
    Unreportable, // Disregarded
    DoubleShot,
    Egoist,
    Energetic,
    Entranced,
    EvilSpirit,
    Examiner,
    Facilitator, // Ghost role
    Finder,
    Flashman,
    Fragile,
    Fool,
    Giant,
    Glow,
    Gravestone,
    GA, // Guardian Angel - Ghost role
    Guesser,
    Haste,
    Haunter, // Ghost role
    Insane,
    Introvert,
    Knighted,
    LastImpostor,
    Lazy,
    Listener,
    Lovers,
    Loyal,
    Lucky,
    Madmate,
    Magnet,
    Mare,
    Messenger,
    Mimic,
    Minion, // Ghost role
    Mischievous,
    Necroview,
    Nimble,
    Noisy,
    Oblivious,
    Onbound,
    Spurt,
    Sleep,
    Specter, // Ghost role
    Physicist,
    Rascal,
    Reach,
    Recruit,
    Rookie,
    Trainee,
    DualPersonality, // Schizophrenic
    Seer,
    Shade, // Ghost role
    Shy,
    Sleuth,
    Sonar,
    Stained,
    TicketsStealer, // Stealer
    Stressed,
    Swift,
    Sunglasses,
    Taskcounter,
    TaskMaster,
    Brakar, // Tiebreaker
    Tired,
    Torch,
    Truant,
    Unbound,
    Undead,
    Underdog,
    Unlucky,
    Venom,
    Warden, // Ghost role
    Watcher,
    Workhorse,
    Youtuber
}